services:
  - type: web
    name: gamevault
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: TRUST_PROXY
        value: "1"
      - key: DATABASE_SSL
        value: "0"
      - key: DATABASE_URL
        fromDatabase:
          name: gamevault-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: APP_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: gamevault-db
    plan: free
    databaseName: gamevault
    user: gamevault
