'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000, DATA=path.join(__dirname,'data.json'), SECRET=process.env.JWT_SECRET||crypto.randomBytes(32).toString('hex');
const initial={users:[],listings:[],offers:[],favorites:[],reports:[],sessions:{}};
let db=(()=>{try{return JSON.parse(fs.readFileSync(DATA,'utf8'))}catch{return structuredClone(initial)}})();
const save=()=>{try{fs.writeFileSync(DATA,JSON.stringify(db))}catch{}};
const json=(res,code,obj)=>{res.writeHead(code,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(obj))};
const body=req=>new Promise((ok,bad)=>{let s='';req.on('data',d=>{s+=d;if(s.length>7e6)req.destroy()});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){bad(e)}});req.on('error',bad)});
const hash=p=>crypto.scryptSync(p,'gv-salt',32).toString('hex');
const token=()=>crypto.randomBytes(24).toString('hex');
function me(req){const c=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('gv_session='));if(!c)return null;const t=c.split('=')[1],id=db.sessions[t];return db.users.find(u=>u.id===id)||null}
function auth(req,res){const u=me(req);if(!u){json(res,401,{error:'Log in required'});return null}return u}
function publicListing(x){const u=db.users.find(a=>a.id===x.sellerId)||{};return {...x,seller:u.username||'unknown',sellerRating:u.rating||5,salesCount:u.salesCount||0}}
function route(req,res){const url=new URL(req.url,'http://x');const p=url.pathname;
 if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true,db:'json-beta',storage:'local'});
 if(req.method==='GET'&&p==='/api/me'){const u=me(req);return json(res,200,u?{id:u.id,username:u.username,email:u.email,role:u.role}:null)};
 if(req.method==='POST'&&p==='/api/signup')return body(req).then(b=>{let {username,email,password}=b;username=(username||'').trim();email=(email||'').trim().toLowerCase();if(username.length<2||!email.includes('@')||(password||'').length<6)return json(res,400,{error:'Check username, email and password'});if(db.users.some(u=>u.email===email||u.username.toLowerCase()===username.toLowerCase()))return json(res,409,{error:'Account already exists'});const u={id:Date.now(),username,email,password:hash(password),role:db.users.length?'user':'admin',rating:5,salesCount:0};db.users.push(u);const t=token();db.sessions[t]=u.id;save();res.setHeader('set-cookie',`gv_session=${t}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000${process.env.NODE_ENV==='production'?'; Secure':''}`);json(res,201,{id:u.id,username:u.username,role:u.role})}).catch(()=>json(res,400,{error:'Bad request'}));
 if(req.method==='POST'&&p==='/api/login')return body(req).then(b=>{const u=db.users.find(x=>x.email===(b.email||'').trim().toLowerCase());if(!u||u.password!==hash(b.password||''))return json(res,401,{error:'Invalid login'});const t=token();db.sessions[t]=u.id;save();res.setHeader('set-cookie',`gv_session=${t}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000${process.env.NODE_ENV==='production'?'; Secure':''}`);json(res,200,{id:u.id,username:u.username,role:u.role})}).catch(()=>json(res,400,{error:'Bad request'}));
 if(req.method==='POST'&&p==='/api/logout'){const c=(req.headers.cookie||'').split(';').find(x=>x.trim().startsWith('gv_session='));if(c)delete db.sessions[c.split('=')[1]];save();res.setHeader('set-cookie','gv_session=; Path=/; Max-Age=0');return json(res,200,{ok:true})}
 if(req.method==='GET'&&p==='/api/listings'){let a=db.listings.filter(x=>x.status==='approved').map(publicListing);const q=(url.searchParams.get('q')||'').toLowerCase(),game=url.searchParams.get('game')||'',max=Number(url.searchParams.get('maxPrice')||0);if(q)a=a.filter(x=>JSON.stringify(x).toLowerCase().includes(q));if(game)a=a.filter(x=>x.game===game);if(max)a=a.filter(x=>x.price<=max);if(url.searchParams.get('verified')==='1')a=a.filter(x=>x.verified);if(url.searchParams.get('noBans')==='1')a=a.filter(x=>!x.bans);if(url.searchParams.get('korblox')==='1')a=a.filter(x=>x.korblox);if(url.searchParams.get('headless')==='1')a=a.filter(x=>x.headless);return json(res,200,a.sort((a,b)=>b.createdAt-a.createdAt))}
 if(req.method==='GET'&&p.startsWith('/api/listings/')){const x=db.listings.find(a=>String(a.id)===p.split('/').pop()&&a.status!=='removed');return x?json(res,200,publicListing(x)):json(res,404,{error:'Not found'})}
 if(req.method==='POST'&&p==='/api/listings'){const u=auth(req,res);if(!u)return;return body(req).then(b=>{const price=Number(b.price),title=(b.title||'').trim();if(title.length<5||!price||price<1)return json(res,400,{error:'Title and price required'});const x={id:Date.now(),sellerId:u.id,title,price,game:b.game||'Roblox',accountYear:Number(b.accountYear)||null,robux:Number(b.robux)||0,bans:Number(b.bans)||0,warnings:Number(b.warnings)||0,korblox:!!b.korblox,headless:!!b.headless,verified:false,tags:Array.isArray(b.tags)?b.tags:[],description:(b.description||'').slice(0,3000),image:(b.image||'').slice(0,5e6),status:u.role==='admin'?'approved':'pending',createdAt:Date.now()};db.listings.push(x);save();json(res,201,x)}).catch(()=>json(res,400,{error:'Bad listing'}))}
 if(req.method==='POST'&&p==='/api/offers'){const u=auth(req,res);if(!u)return;return body(req).then(b=>{const l=db.listings.find(x=>x.id===Number(b.listingId)&&x.status==='approved');if(!l)return json(res,404,{error:'Listing unavailable'});if(l.sellerId===u.id)return json(res,400,{error:'Cannot offer on your own listing'});const o={id:Date.now(),listingId:l.id,buyerId:u.id,sellerId:l.sellerId,amount:Number(b.amount),status:'pending',createdAt:Date.now()};db.offers.push(o);save();json(res,201,o)}).catch(()=>json(res,400,{error:'Bad offer'}))}
 if(req.method==='POST'&&p.startsWith('/api/favorites/')){const u=auth(req,res);if(!u)return;const id=Number(p.split('/').pop()),k=db.favorites.findIndex(f=>f.userId===u.id&&f.listingId===id);let favorited;if(k>=0){db.favorites.splice(k,1);favorited=false}else{db.favorites.push({userId:u.id,listingId:id});favorited=true}save();return json(res,200,{favorited})}
 if(req.method==='POST'&&p==='/api/reports'){const u=auth(req,res);if(!u)return;return body(req).then(b=>{db.reports.push({id:Date.now(),listingId:Number(b.listingId),reporterId:u.id,reason:String(b.reason||'').slice(0,1000),status:'open',createdAt:Date.now()});save();json(res,201,{ok:true})}).catch(()=>json(res,400,{error:'Bad report'}))}
 if(req.method==='GET'&&p==='/api/dashboard'){const u=auth(req,res);if(!u)return;const mine=db.listings.filter(x=>x.sellerId===u.id).map(publicListing),fav=db.favorites.filter(f=>f.userId===u.id).map(f=>db.listings.find(x=>x.id===f.listingId)).filter(Boolean).map(publicListing);const enrich=o=>({...o,title:(db.listings.find(x=>x.id===o.listingId)||{}).title,buyer:(db.users.find(x=>x.id===o.buyerId)||{}).username,seller:(db.users.find(x=>x.id===o.sellerId)||{}).username});return json(res,200,{mine,favorites:fav,offersIn:db.offers.filter(o=>o.sellerId===u.id).map(enrich),offersOut:db.offers.filter(o=>o.buyerId===u.id).map(enrich)})}
 if(req.method==='PATCH'&&p.startsWith('/api/offers/')){const u=auth(req,res);if(!u)return;return body(req).then(b=>{const o=db.offers.find(x=>String(x.id)===p.split('/').pop()&&x.sellerId===u.id);if(!o)return json(res,404,{error:'Offer not found'});if(!['accepted','declined'].includes(b.status))return json(res,400,{error:'Invalid status'});o.status=b.status;if(b.status==='accepted'){const l=db.listings.find(x=>x.id===o.listingId);if(l)l.status='reserved';db.offers.filter(x=>x.listingId===o.listingId&&x.id!==o.id&&x.status==='pending').forEach(x=>x.status='declined')}save();json(res,200,{ok:true})}).catch(()=>json(res,400,{error:'Bad request'}))}
 if(req.method==='GET'&&p==='/api/admin'){const u=auth(req,res);if(!u)return;if(u.role!=='admin')return json(res,403,{error:'Admin only'});return json(res,200,{pending:db.listings.filter(x=>x.status==='pending').map(publicListing),reports:db.reports.filter(x=>x.status==='open').map(r=>({...r,title:(db.listings.find(x=>x.id===r.listingId)||{}).title,reporter:(db.users.find(x=>x.id===r.reporterId)||{}).username}))})}
 if(req.method==='PATCH'&&p.startsWith('/api/admin/listings/')){const u=auth(req,res);if(!u)return;if(u.role!=='admin')return json(res,403,{error:'Admin only'});return body(req).then(b=>{const l=db.listings.find(x=>String(x.id)===p.split('/').pop());if(!l)return json(res,404,{error:'Not found'});l.status=b.status==='approved'?'approved':'rejected';save();json(res,200,{ok:true})})}
 if(req.method==='PATCH'&&p.startsWith('/api/admin/reports/')){const u=auth(req,res);if(!u)return;if(u.role!=='admin')return json(res,403,{error:'Admin only'});const r=db.reports.find(x=>String(x.id)===p.split('/').pop());if(r)r.status='resolved';save();return json(res,200,{ok:true})}
 if(req.method==='GET'){let file=p==='/'?'index.html':p.slice(1);if(!file.includes('.')||file.includes('..'))file='index.html';const f=path.join(__dirname,'public',file);if(fs.existsSync(f)){const ext=path.extname(f),ct=ext==='.css'?'text/css':ext==='.js'?'application/javascript':'text/html';res.writeHead(200,{'content-type':ct});return fs.createReadStream(f).pipe(res)}const i=path.join(__dirname,'public','index.html');res.writeHead(200,{'content-type':'text/html'});return fs.createReadStream(i).pipe(res)}
 json(res,404,{error:'Not found'});
}
http.createServer((req,res)=>{Promise.resolve(route(req,res)).catch(e=>{console.error(e);json(res,500,{error:'Server error'})})}).listen(PORT,()=>console.log('GameVault beta on',PORT));
